# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver:
#   gem install mysql2
# On macOS with Homebrew:
#   brew install mysql
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: piano_web_app_development

test:
  <<: *default
  database: piano_web_app_test

production:
  <<: *default
  database: piano_web_app_production
  username: piano_web_app
  password: <%= ENV["PIANO_WEB_APP_DATABASE_PASSWORD"] %>
